### PR TITLE
Bugfix: removed admin role change bug

### LINKED ISSUE #38: Admin role should not be able to be disabled
**Description:** 
Users with the role of "admin" should not be able to be disabled.

Screen Shot 2022-05-27 at 2 28 04 PM

Screen Shot 2022-05-27 at 2 27 53 PM

Screen Shot 2022-05-27 at 2 30 56 PM

**Priority:** 
Low

**Size Estimation:** 
Size: 7

**Origin:** 
System Testing

### LINKED ISSUE #40: Admin should not be able to change its own role
**Description:** 
The admin should be able to change the role of a registered User to "Staff" or "User" but should not be able to change its own role.

Screen Shot 2022-05-27 at 2 28 31 PM
Screen Shot 2022-05-27 at 2 28 04 PM

**Priority:** 
Low

**Size estimation:** 
Size: 20

**Origin:** 
System Testing

### PR DESCRIPTION
**Pull request by chloe-blankers**
Screen Shot 2022-06-28 at 4 02 18 PM

It seems this fix would prevent the admin from being disabled as well as being able to change roles. So I linked both of those issues. Please test as well to verify this is the case.

### CODE REVIEW

File: src/components/pages/AdminPanel.js [hunk 1]
```diff
@@ -27,11 +27,16 @@ const AdminPanel = (props) => {
 
 
 	const changeRole = (evt, username) => {
-		console.log(evt.target.value, username)
-		var role = evt.target.value
-		changeAccountRole(username, role, user.jwt)
-		.then(resp => 
-			console.log("Changed Roles"))
+		if(username === "admin@venus.com"){
+			alert("Admin user is not permitted to change roles.")
```
Comment (joshmorg1007) [inline src/components/pages/AdminPanel.js]: small nitpick, but maybe should specify that the admin user is not permitted to change their own role, the current error message could be inferred as the admin user is not permitted to change any users roles.

**Review by joshmorg1007 — APPROVED** [review]

File: src/components/pages/AdminPanel.js (hunk 1 above)
Comment (chloe-blankers) [reply src/components/pages/AdminPanel.js]: changed it to "Admin user is not permitted to change its own role."
